# generated by datamodel-codegen:
#   filename:  l.json
#   timestamp: 2022-11-03T22:40:15+00:00

from __future__ import annotations

from typing import Any, Dict, List, Optional

from pydantic import BaseModel


class ExternalUrls(BaseModel):
    spotify: str


class Followers(BaseModel):
    href: str
    total: int


class Image(BaseModel):
    url: str
    height: Optional[int]
    width: Optional[int]


class ExternalUrls1(BaseModel):
    spotify: str


class Followers1(BaseModel):
    href: str
    total: int


class Owner(BaseModel):
    external_urls: ExternalUrls1
    # followers: Followers1
    href: str
    id: str
    type: str
    uri: str
    display_name: str


class Tracks(BaseModel):
    href: str
    items: List[Dict[str, Any]]
    limit: int
    next: str
    offset: int
    previous: str
    total: int


class PlaylistResponseModel(BaseModel):
    collaborative: bool
    description: str
    external_urls: ExternalUrls
    # followers: Followers
    href: str
    id: str
    images: List[Image]
    name: str
    owner: Owner
    public: bool
    snapshot_id: str
    # tracks: Tracks
    type: str
    uri: str
